### ISSUE TITLE
Blank page rendering

### ISSUE THREAD

**Issue by twd3** [aryehraber/statamic-logbook#10]
Log content flashes for a minute after clicking logbook link under utilities then I get a blank page.

**Comment by twd3** [comment]
No, it just does that on local I think it's working on server. The only thing I see that's weird is the drop arrow for the log select is whacked for me.
![sdf](https://user-images.githubusercontent.com/16004958/91092444-4421f800-e615-11ea-99af-79176fcaeef0.jpg)

**Comment by aryehraber** [comment]
Hey @twd3, thanks for reporting, I think I know what the arrow issue is... fix coming soon!
