### ISSUE TITLE
logbook displays momentarily then whole page renders as background color with no content

### ISSUE THREAD

**Issue by nn-dmt** [aryehraber/statamic-logbook#11]
PHP Version | 7.3.7

<img width="1280" alt="Screen Shot 2020-12-09 at 7 06 22 PM" src="https://user-images.githubusercontent.com/75390655/101716192-a7fbef80-3a51-11eb-9624-0951e5f3022e.png">

**Comment by aryehraber** [comment]
Hi @nn-dmt, could you please share some more details about your setup:

- Statamic version
- Logbook addon version
- Have you successfully completed the [installation instructions](https://github.com/aryehraber/statamic-logbook#installation)? 

I've tested on the latest Statamic version and everything seems to work as expected on my end, so any extra details would be useful in debugging. Thanks!

**Comment by nn-dmt** [comment]
Hi Aryehraber,

Yes, I have completed all the instructions - and the logbook worked when I first installed it but hasn't since I updated statamic. Like mentioned previously, the logbook UI actually loads for a moment, about 1 second, before the page goes blank.

Here is some more information:


Statamic | 3.0.34 | Up to date
-- | -- | --
ColorExtractor | 1.1.2 | Up to date
FontAwesome | 2.0.0 | Up to date
Impersonator | 2.0.0 | Up to date
Logbook | 2.0.1 | Up to date
Instagram Feed | 2.2.0 | Up to date
Duplicator | 1.2.1 | Up to date
Markdown Highlight | 1.0.4 | Up to date
Responsive Images | 1.4.0 | Up to date
Export | 1.0.3 | Up to date

**Comment by nn-dmt** [comment]
Hey Aryehraber,

Here is a new update with more information. I checked the dev tools in my browser which gave more insight where the page breaks:
<img width="1472" alt="Screen Shot 2020-12-13 at 7 53 40 PM" src="https://user-images.githubusercontent.com/75390655/102038785-00e2c500-3d7d-11eb-8460-0041979f7853.png">

**Comment by aryehraber** [comment]
Hi @nn-dmt, thanks for sharing more info., though this screenshot isn't all that useful tbh. Are there any console errors? 

I've not been able to reproduce the issue on my end on latest Statamic in Chrome & Safari. 

If you're able, could you try and create a fresh Statamic project and install the addon again to see if it still happens?

**Comment by nn-dmt** [comment]
Hi @aryehraber and sorry that they were not helpful, 

Here is a screenshot of the web console output from the dev tools:
<img width="1886" alt="Screen Shot 2020-12-14 at 1 32 51 PM" src="https://user-images.githubusercontent.com/75390655/102138258-ef4afd00-3e10-11eb-826c-75eaeac26273.png">

I will try some more troubleshooting with a fresh projects, but this only happened after I either did a composer update or installed another addon - but i am not exactly sure when logbook stopped functioning.

**Comment by aryehraber** [comment]
Hmm very odd, sorry I can't be more helpful to debug atm. 

FYI: I also just tried in latest Firefox (v.84) locally and it seems to still be working as expected.

Feel free to add more details if you are able to reliably reproduce in a fresh project. Thanks!

**Comment by nn-dmt** [comment]
Hey @aryehraber 

I was able to reproduce the bug on a fresh install, on a digital ocean droplet. The logbook worked for a long time but today suddenly stopped working, and I think it might have something to do with Form / field errors - because that's the only thing I was changing in my antlers templates this morning, and when I visit the logbook before it disappears i see some error about form {{ field }}.


https://user-images.githubusercontent.com/75390655/103159195-25766e00-477b-11eb-8f67-54673fb94b91.mov

**Comment by thisJerem** [comment]
Hi @aryehraber !

I just had the same issue, which apply to any browsers. It seems the vue.common.js fail at some point when he need a value from parent_uri.
Here is a quick recording :
https://www.loom.com/share/f0ff02196f0241c498828fa9c2ca72f1

If you want I can provide you a test account on my testing repo ;)

**Comment by aryehraber** [comment]
Hi @thisJerem, thanks for supplying a screen recording; still not quite sure what's going on... My best guess is that some of the log output is not playing nice with Statamic/Vue.

I don't think I need access to a test repo, as I'm fairly sure it's caused by the contents of the log file itself, are you able to share your log file(s)? Please make sure to remove any sensitive data before sharing the file publicly, and then double check that the sanitised log is still causing issues. Thanks!

**Comment by thisJerem** [comment]
Thanks you aryehraber !
I was pretty sure that was indeed some content that Vue don't like to parse.

Here is my laravel.log file cleaned from all sensitive data :)
[laravel.log](https://github.com/aryehraber/statamic-logbook/files/6532828/laravel.log)

**Comment by aryehraber** [comment]
This issue should now be solved! Please update to the latest release available on Statamic's Marketplace: https://statamic.com/addons/aryeh-raber/logbook/release-notes

@thisJerem Thanks for sharing your log file, it really helped! It ended up being caused by Statamic's Antler syntax `{{` inside the log output, which then messed up Vue's parser.

**Comment by thisJerem** [comment]
Thanks you @aryehraber ! I just deploy last version to my server and can confirm this is perfectly working !
