### ISSUE TITLE
Internationalization gets forced to English in Statamic

### ISSUE THREAD

**Issue by RheaMars** [aryehraber/statamic-logbook#12]
**Bug description:**

When installing the addon some CP translations are forced to fallback to English.
Translations  requested by e.g. `__('statamic::messages.forgot_password_enter_email')` still work, but translations requested e.g. by `__('Forgot Your Password?')` do not.
The translations show up again as soon as you uninstall the addon.

**Environment:**

Statamic 3.0.40 Pro
Laravel 8.24.0
PHP 7.4.10
aryehraber/statamic-logbook

**See also:**

https://github.com/aryehraber/statamic-impersonator/issues/8
https://github.com/statamic/cms/issues/3127

**Comment by aryehraber** [comment]
Thanks for opening the issue here @RheaMarst! I just commented on the Statamic repo issue so will hopefully get an answer soon to fix this problem.

**Comment by aryehraber** [comment]
Closing due to this being an old issue. I've just released v3.0.0 with Statamic 4 support which changed how Utilities get booted up -- hoping this change also fixes the issue. Feel free to re-open if the issue persists on the latest version.
