### ISSUE TITLE
Version 2.1.0 errors on Statamic 3.4.X

### ISSUE THREAD

**Issue by dniccum** [aryehraber/statamic-logbook#15]
After upgrading our Statamic installation to 3.4.5 (PHP 8.1), the addon began erroring with the following error message.

We are using Laravel 9.52.4.

```
AryehRaber\Logbook\LogbookController::sanitize(): Argument #1 ($log) must be of type array, null given, called in /home/vagrant/Sites/schier-products-website/vendor/aryehraber/statamic-logbook/src/LogbookController.php on line 22
```

**Comment by aryehraber** [comment]
Hi @dniccum, thanks for reporting this issue! 

I wasn't able to recreate the scenario you described, however I added an empty array as a fallback so that it shouldn't be possible anymore. Feel free to re-open if you continue having issues after updating to v2.2.0.
