### ISSUE TITLE
Logbook now appears in "unlisted addon"

### ISSUE THREAD

**Issue by imbwaldo** [aryehraber/statamic-logbook#19]
As of Statamic 4.18.0, Logbook is showing up under "unlisted addons" in the Updates tab:

<img width="526" alt="Screenshot 2023-08-22 at 1 12 41 PM" src="https://github.com/aryehraber/statamic-logbook/assets/1582379/4cc023b6-370e-4ad8-8f88-1a3fab2dd16e">

Seems like things are still working, but I'm not sure what to make of it. Thought I'd let you know. Is there anything I need to do?

**Comment by aryehraber** [comment]
Thanks for the heads up! Perhaps I've missed a recent API change or something, will investigate this week.

**Comment by imbwaldo** [comment]
Thanks! I didn't give you any information about my setup. Hope this helps:

Environment
Application Name: Statamic
Laravel Version: 9.52.15
PHP Version: 8.1.22
Composer Version: 2.5.8
Environment: local
Debug Mode: OFF
URL: world-concern-statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.18.0 PRO

Statamic Addons
aryehraber/statamic-logbook: 3.1.0
mitydigital/feedamic: 2.2.6
rias/statamic-redirect: 3.1.0
spatie/statamic-responsive-images: 4.1.1
statamic/seo-pro: 5.2.2
visuellverstehen/statamic-classify: 2.6.1

**Comment by imbwaldo** [comment]
Looks like this is only an issue in my local dev environment. On the live site, all looks as it should.

**Comment by aryehraber** [comment]
Haha no worries, thanks for the follow up 👍
