### ISSUE TITLE
Statamic v5 Support

### ISSUE THREAD

**Issue by dryven-daniel** [aryehraber/statamic-logbook#22]
Hi there, thanks for this great addon!

Will you add support for Statamic v5?

**Comment by aryehraber** [comment]
Hi @dryven-daniel! Thanks, glad to hear it's been useful so far!

I released [v3.3.0](https://github.com/aryehraber/statamic-logbook/releases/tag/v3.3.0) a few weeks ago which should have added Statamic v5 support. Is it not working for you?

**Comment by dryven-daniel** [comment]
Hi @aryehraber, my bad... works fine. Thank you!

**Comment by aryehraber** [comment]
Great, thanks for following up 👍
