### ISSUE TITLE
FR: Update to use Tailwind

### ISSUE THREAD

**Issue by edalzell** [aryehraber/statamic-logbook#8]
V3 uses Tailwind & Vue2 in the CP, are you planning on updating to support that?

**Comment by aryehraber** [comment]
Yeah totally! Once I get my hands on the beta, I'll slowly start upgrading my addons and follow whatever new/updated conventions that they follow/recommend; Tailwind & Vue 2 sound 👌

**Comment by aryehraber** [comment]
New V3 release is using TW 😄
